### ISSUE TITLE
How to add and activate the Arabic language

### ISSUE THREAD

**Issue by Arabiain** [mjau-mjau/files.photo.gallery#17]
Hello my friend
Thank you very much for this excellent and very useful script. I did not know how to activate the Arabic language and I am ready to translate the text into Arabic. Please explain how to activate and add the Arabic language file, thank you very much.

**Comment by mjau-mjau** [comment]
Hi. If you want to use Github, you can create a new file `ar.json` in https://github.com/mjau-mjau/files.photo.gallery/tree/master/lang, based on [English](https://github.com/mjau-mjau/files.photo.gallery/blob/master/lang/en.json) (empty) or [German](https://github.com/mjau-mjau/files.photo.gallery/blob/master/lang/de.json) (populated).

Or just download the English `en.json` file, duplicate it to `ar.json` and translate it:
https://cdn.jsdelivr.net/npm/files.photo.gallery@0.7.0/lang/en.json

Populated example in German:
https://cdn.jsdelivr.net/npm/files.photo.gallery@0.7.0/lang/de.json

After translating, please send the file to me, and I will include it as an official language. Until it's included by me, you would have to add the language manually to your Files gallery installation. See docs:
https://www.files.gallery/docs/language/#adding-new-custom-language

Thanks.

**Comment by Arabiain** [comment]
Thank you very much, I will attach the file to you after it has been translated
I have another question, is it possible to run this script on a localhost server that is not connected to the Internet?
[ar.zip](https://github.com/mjau-mjau/files.photo.gallery/files/9445918/ar.zip)

**Comment by Arabiain** [comment]
Thank you very much
![image](https://user-images.githubusercontent.com/8568779/187239794-0cd56e74-c96b-4c5a-8bd8-117082080315.png)

![image](https://user-images.githubusercontent.com/8568779/187239609-0db17bbf-c0bc-4234-8c09-e81eb51d0284.png)

**Comment by mjau-mjau** [comment]
> is it possible to run this script on a localhost server that is not connected to the Internet?

Yes. Since [version 0.6.0](https://www.files.gallery/blog/files-0-6-0/), you can host all external assets (Javascript + CSS) on your own server (for example localhost). See instructions:
https://www.files.gallery/docs/self-hosted-assets/

**Comment by Arabiain** [comment]
Thank you very much, the best file script ever, awesome, fast, powerful, beautiful
It works without the need to connect to the Internet

![image](https://user-images.githubusercontent.com/8568779/187473811-f0ba88be-75ce-4427-9228-1102f1e026b6.png)

**Comment by mjau-mjau** [comment]
> I noticed that it does not search within subfolders, it needs this feature as well as searching inside files, especially php, which is very necessary, as well as the search and replace feature and others.

This is currently a "filter", to search/filter files in current dir, and that's why it's so fast/instant. I would like to integrate "global search", but that is an entirely different process that must connect to PHP to search all files in all dirs ... This process would be very slow if you have an extensive folder structure, and the only way around that would be to use some JSON/Database caching index. Even desktop apps need to index files for faster searching ... It's too slow to search realtime, like in your case when you have the entire "www" folder structure as `root`.

I will be considering it, but there are some challenges ... 

PS! Please post questions and comments in our forums. I don't really use use Github for support or requests.
https://forum.files.gallery/

**Comment by mjau-mjau** [comment]
Arab lang contribution was included in latest [Files Gallery 0.8.0](https://www.files.gallery/blog/files-0-8-0/), thanks.
