### ISSUE TITLE
Create custom link for sharing

### ISSUE THREAD

**Issue by dotcomUNDERGROUND** [mjau-mjau/files.photo.gallery#18]
Like the "Open in new tab" where the file URL gets open in a new window, I want to open it to my external share URL like site.com/share.php?link={full link of the file}

How can I do it?

Following https://forum.files.gallery/d/160-how-into-asig-to-item-action-call-exrternal-function/3 I have been able to create the menu item (just copy pasting your code). But how do I write the actual function?

**Comment by mjau-mjau** [comment]
Yes it's possible, but please post this in the [forums](https://www.files.gallery/), and I will answer it.

There is additional info about custom links below:
https://www.files.gallery/docs/javascript-config/

For button that is a link (points to your own `share.php`), you would use the `href` property, and not the `action` property, because you will be opening a link, not running a function inside Files.
