### ISSUE TITLE
contributing to files.js 

### ISSUE THREAD

**Issue by tolgaulas** [mjau-mjau/files.photo.gallery#24]
@mjau-mjau: Would it be possible to have files.js un-minified so that we can contribute on it..  For example, options to modify the parameters of Codemirror for linters etc..

**Comment by mjau-mjau** [comment]
Sorry no. You can request API access features for CodeMirror, similar to what is already offered for many other plugins:
https://www.files.gallery/docs/javascript-config/

I don't want to and don't intend to offer the javascript source code files. Not only because they are not made for public or because I don't want it exposed, but also because in the case of quite specific javascript, it's not useful to have contributions for opinionated features that may clutter further development.
